name: CD - Despliegue a GitHub Pages

on:
  push: # TODO 1: Se activa al fusionar (hacer push) en main
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # TODO 2: Permiso para crear la rama gh-pages
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # TODO 3: Directorio actual (raíz)
          publish_branch: gh-pages